In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,4,5])
a

array([1, 2, 3, 4, 4, 5])

In [4]:
a.size
a.shape
a.ndim
a.dtype

dtype('int64')

In [5]:
a.size

6

In [6]:
a.shape

(6,)

In [7]:
a.dtype

dtype('int64')

In [8]:
a[0]

1

In [9]:
a[0,]

1

# NOTE that both a[0] and a[0,] prints the same thing for this 1D array.

# NOTE remember that we can always use slicing in arrays and in pandas so make heavy use of it. TODO - how doe sslicing works internally? any performance considerations here???

In [10]:
a[:4]

array([1, 2, 3, 4])

In [11]:
np.save('amit',a)

# NOTE here first parameter is the name of the file that we want to save as and second is the actual array. TODO - so if arrays can eb saved to the disk then what is the performance consideration of keeping them in memory? when we work with really big data then how much of that is really kept in memory.

In [12]:
np.load('amit.npy')

array([1, 2, 3, 4, 4, 5])